from .traj_field import compare_error_field,compare_error_traj
from .slice import compare_error_field_slice, compare_error_traj_slice
from .frame import compare_error_traj_frame
from .frame_slice import compare_error_traj_frame_slice